Task: Export selected resources to postman collection
microsoftgraph/microsoft-graph-explorer-v4 pull request #1277
Opened 2021-11-30 16:51 UTC by thewahome

## Overview

Fixes #1110 
Fixes #1111 

### Demo

Optional. Screenshots, `curl` examples, etc.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output

2021-12-01 06:36 UTC, jobala commented on src/app/views/sidebar/resource-explorer/CommandOptions.tsx
> +      onClick: () => console.log('info')
Did this snuck through? Or there by design?

2021-12-01 06:59 UTC, jobala requested changes

2021-12-01 06:59 UTC, jobala commented on src/app/services/reducers/resources-reducer.ts
> +          paths.push(element);
Performing side effects in a reducer leads to hard to debug bugs. You can avoid the side-effect with `paths = [...paths, element]` which creates a new copy of the variable.

2021-12-01 06:59 UTC, jobala commented on src/app/services/reducers/resources-reducer.ts
> +        list.splice(i, 1);
Create a new copy of list instead of mutating it.

2021-12-01 06:59 UTC, jobala commented on src/app/views/sidebar/resource-explorer/panels/Paths.tsx
> +export default class Paths extends Component<any, any> {
Consider using appropriate types for the props and state.

2021-12-01 06:59 UTC, jobala commented on src/app/views/sidebar/resource-explorer/panels/postman.util.ts
> +function generatePostmanCollection(paths: any[]): IPostmanCollection {
Using any turns off type checking. Use appropriate type.

2021-12-01 06:59 UTC, jobala commented on src/app/views/sidebar/resource-explorer/ResourceExplorer.tsx
> +      case 'add-to-collection':
Consider making this an enum `ResourceOptions.ADD_TO_COLLECTION`

2021-12-01 07:05 UTC, jobala requested changes
I noticed a bug where by deleting a collection does not clear the toggle/checkbox and users might mistakenly think that the delete action was unsuccesful.

My recommendations are;
1. Let's clear the toggle/checkbox after a delete action
2. Let's provide the user with visual feedback regarding the state of the delete action ie `Resource deleted successfuly` or `Resource could not be deleted`

2021-12-01 18:56 UTC, Onokaev commented on src/app/views/sidebar/resource-explorer/panels/postman.util.ts
> +  return content;
Must have left this here by mistake :)

2021-12-01 18:56 UTC, Onokaev commented on src/app/views/sidebar/resource-explorer/panels/PathsReview.tsx
> +        </PrimaryButton>
The text is missing in GE.json file

2021-12-02 07:37 UTC, jobala approved these changes

2021-12-02 11:21 UTC, Onokaev approved these changes

2021-12-02 12:15 UTC, merged