Chore: Update MsGraph JavaScript SDK
microsoftgraph/microsoft-graph-explorer-v4 pull request #1568
Opened 2022-03-16 17:17 UTC by ElinorW

## Overview

update `@microsoft/microsoft-graph-client` to `v3.0.2`

Fixes #1545

2022-03-31 12:23 UTC, thewahome approved these changes
Ship it!

2022-03-31 12:31 UTC, thewahome requested changes
I have just noticed that in private mode authentication fails until I reload the page.
The error shown is:

Error: Failed to get profile information- Error: no_account_error: No account object provided to acquireTokenSilent and no active account has been set. Please call setActiveAccount or provide an account on the request.
    at _callee2$ (webpack-internal:///./src/app/services/actions/profile-action-creators.ts:139:19)

2022-03-31 13:57 UTC, ElinorW commented
> I have just noticed that in private mode authentication fails until I reload the page. Note: I successfully sign in but can not get the profile. On reload, the page is able to successfully get my profile and I stay signed in.
> 
> The error shown is:
> 
> Error: Failed to get profile information- Error: no_account_error: No account object provided to acquireTokenSilent and no active account has been set. Please call setActiveAccount or provide an account on the request. at _callee2$ (webpack-internal:///./src/app/services/actions/profile-action-creators.ts:139:19)

Great, I'll have a look at this

2022-04-06 15:28 UTC, Onokaev approved these changes

2022-04-07 05:45 UTC, merged