Task: Add missing header telemetry
microsoftgraph/microsoft-graph-explorer-v4 pull request #1944
Opened 2022-07-20 08:08 UTC by ElinorW

## Overview

Fixes #1943 
This PR adds telemetry to measure clicks on the Settings button, Help button, Sign in button and the Sign in with a different account button.

2022-07-20 09:49 UTC, millicentachieng requested changes

2022-07-20 09:49 UTC, millicentachieng commented on src/telemetry/component-names.ts
> +export const SIGN_IN_WITH_OTHER_BUTTON = 'Sign in with other button';
For clarity, can we rename this to 'Sign in with other account button'?

2022-07-21 15:19 UTC, millicentachieng approved these changes

2022-07-21 15:46 UTC, Onokaev approved these changes

2022-07-22 09:01 UTC, merged