Feature: ABNF validation
microsoftgraph/microsoft-graph-explorer-v4 pull request #2044
Opened 2022-08-16 15:05 UTC by thewahome

## Overview

ABNF odata parser generation

2022-09-07 20:40 UTC, gavinbarron commented on src/modules/validation/abnf.ts
> +import { apgApi, apgLib } from 'apg-js';
```suggestion
import { apgApi, apgLib } from 'apg-js/dist/apg-api-bundle.js';
```

2022-09-30 10:10 UTC, ElinorW commented on package.json
> +                "apg-js": "^4.1.2",
don't forget to remove the caret

2022-09-30 10:15 UTC, ElinorW approved these changes

2022-10-10 20:32 UTC, gavinbarron requested changes
This is looking good, but I think there's a little bit of clean up to get it ready to release

2022-10-11 09:33 UTC, Onokaev approved these changes

2022-10-12 06:50 UTC, merged