Fix: missing paths available in resource tree
microsoftgraph/microsoft-graph-explorer-v4 pull request #2821
Opened 2023-10-11 14:25 UTC by thewahome

## Overview

Fixes #2820

### Demo

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/58787602/414ac289-9993-45c5-94fe-a3296eb04fa8)

### Notes

/places does not have indicators of which version it belongs to. Hence it will not be visible in the list

## Testing Instructions

* Check for sites as one of the root nodes
* Confirm GET sites as one of the children

2023-10-12 12:13 UTC, ElinorW commented
Also clicking on the search items results in this error 
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/18407044/ceaf672c-7c69-43b6-9e89-880532c39580)

2023-10-16 19:41 UTC, ElinorW commented on src/app/views/sidebar/resource-explorer/resource-explorer.utils.ts
> +      versionedChildren && versionedChildren.length > 1
This line hinders the counter displaying when a user searches for a resource and the parent node has only 1 child that matches the search term. 
Leaving it as it was ensures the counter always displays
```suggestion
      versionedChildren && versionedChildren.length > 0
```

2023-10-16 19:41 UTC, ElinorW requested changes

2023-10-16 19:41 UTC, ElinorW commented on src/app/views/sidebar/resource-explorer/resource-explorer.utils.ts
> +      links: versionedChildren.length > 1 ? versionedChildren : [],
This also disrupts the search as parent nodes with one child can't expand...
leaving it as `links: versionedChildren`  fixes the issue
```suggestion
      links: versionedChildren,
```

2023-10-17 11:38 UTC, thewahome commented
Closing this as the work handled here has also been taken care of by https://github.com/microsoftgraph/microsoft-graph-explorer-v4/pull/2680

2023-10-17 11:38 UTC, closed without merging