Chore: Release 10.4.0
microsoftgraph/microsoft-graph-explorer-v4 pull request #3283
Opened 2024-08-19 10:03 UTC by thewahome

## Overview

2024-08-20 15:16 UTC, ElinorW requested changes
Clicking on the resources tab causes the app to crash

2024-08-26 11:55 UTC, ElinorW approved these changes

2024-08-26 15:05 UTC, ElinorW approved these changes

2024-08-27 15:15 UTC, musale approved these changes

2024-09-02 15:51 UTC, merged