Task: retrigger suggestions using key combinations
microsoftgraph/microsoft-graph-explorer-v4 pull request #718
Opened 2020-10-01 15:17 UTC by thewahome

## Overview

In case you delete something and want to retrigger the suggestions, you can use `CMD+.` / `CTRL+.` / `CTRL+space` / `CMD+space`

2020-10-06 07:06 UTC, jobala requested changes

2020-10-06 07:06 UTC, jobala commented on src/app/views/query-runner/query-input/AutoComplete.tsx
> +    console.log({ input: e.target.value, userInput: previousUserInput, compare })
This one sneaked through.

2020-10-06 07:06 UTC, jobala commented on src/app/views/query-runner/query-input/AutoComplete.tsx
> +    if (controlSpace || controlPeriod) {
You can combine the ifs 

```javascript
if ((controlSpace || controlePeriod) && suggestions.length) {
    ...
}
```

2020-10-08 14:11 UTC, thewahome commented on src/app/views/query-runner/query-input/AutoComplete.tsx
> +    console.log({ input: e.target.value, userInput: previousUserInput, compare })
Nice catch!

2020-10-12 06:26 UTC, jobala approved these changes

2020-10-12 08:45 UTC, merged