Task:cache results
microsoftgraph/microsoft-graph-explorer-v4 pull request #759
Opened 2020-11-10 12:49 UTC by thewahome

## Overview

Uses indexed db to store the results of the autocomplete query so that subsequent calls do not call the API.

### Demo

![image](https://user-images.githubusercontent.com/58787602/98675361-343fc780-236b-11eb-9ff6-020d4593ee93.png)

### Notes

Request URLs with keys are replaced with generic IDs so that they are easily recreated for storage and searching in the cache.

### Tasks

- [x] Create store for autocomplete options
- [x] Read and write options to the store
- [ ] Add a time to live for the options in the store

## Testing Instructions

* Run the app. Trigger an autocomplete search e.g me/messages?
* Using the developer console, notice that the request URL is placed as a key in the indexedDb storage
* perform another autocomplete search e.g me/todo?
* Using the developer console, notice that there was a network request that was made
* Redo me/messages? and notice that it is no longer calling the API

2020-11-11 11:56 UTC, jobala commented on src/app/views/query-runner/query-input/auto-complete/auto-complete.cache.ts
> +export async function getAutoCompleteContentFromCache(url: string) {
Specify return type.

2020-11-11 12:11 UTC, jobala requested changes
It is possible to improve storage performance by storing the hash of a path instead of the path itself because in the worst case scenario the path can be really long.

2020-11-11 12:11 UTC, jobala commented on src/app/views/query-runner/query-input/auto-complete/auto-complete.cache.ts
> +  const ageInDays: number = 7;
I think you can leave out the type here to be consistent or specify the type for all variable assignments.

2020-11-11 12:14 UTC, jobala commented
#### Design Proposal

@thewahome what do you think of abstracting the logic for fetching suggestions into a SuggestionProvider module that has the simple interface `getSuggestion(...)` then under the hood it will figure out whether to get the suggestion from cache or network.

Ideally, someone else with a similar use case should be able to use this module without understanding how it works.

Let me know what you think.

2020-11-12 10:00 UTC, thewahome commented
> #### Design Proposal
> @thewahome what do you think of abstracting the logic for fetching suggestions into a SuggestionProvider module that has the simple interface `getSuggestion(...)` then under the hood it will figure out whether to get the suggestion from cache or network.
> 
> Ideally, someone else with a similar use case should be able to use this module without understanding how it works.
> 
> Let me know what you think.

@jobala this sounds good and worth looking into... We can track this as technical debt?

2020-11-12 10:19 UTC, jobala commented
> @jobala this sounds good and worth looking into... We can track this as technical debt?

@thewahome if it was up to me I would say we do this before merging. I will leave it up to @ddyett and @MIchaelMainer to make the call.

2020-11-13 10:40 UTC, jobala commented on src/modules/suggestions/suggestions.ts
> +  public async fetchSuggestionsFromNetwork(url: string, api: string): Promise<IParsedOpenApiResponse | null> {
This method should be private.

2020-11-13 10:44 UTC, jobala approved these changes

2020-11-13 10:59 UTC, merged