FIX: trim space in URL before executed
microsoftgraph/microsoft-graph-explorer-v4 pull request #827
Opened 2021-02-02 15:47 UTC by ezkemboi

- Fixes #788

## Overview

Brief description of what this PR does, and why it is needed.

### Demo

Optional. Screenshots, `curl` examples, etc.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output

2021-02-03 17:42 UTC, jobala commented
Instead of running this magically should we instead have a url validation error message?

2021-02-03 17:54 UTC, ezkemboi commented
@baywet any comment on @jobala suggestion?

2021-02-03 18:03 UTC, baywet requested changes
The current implement would replace spaces within the URL, which is not valid, for example some odata query parameters can contain spaces and that'd be valid. I think we should only consider the spaces at the end and the beginning so the request isn't changed and doesn't fail because of a typo

2021-02-03 18:03 UTC, baywet commented on src/app/views/query-runner/QueryRunner.tsx
> +      sampleQuery.sampleUrl = sampleQuery.sampleUrl.replace(/\s+/g, '');
```suggestion
      sampleQuery.sampleUrl = sampleQuery.sampleUrl.trim();
```

2021-02-03 18:54 UTC, ezkemboi commented
Changes updated accordingly.

2021-02-03 19:16 UTC, baywet approved these changes

2021-02-03 23:01 UTC, jobala commented
@ezkemboi @baywet trimming the whitespaces doesn't solve this issue. Odata query parameters come after the `?`. @ezkemboi can you implement a URL validator for the path before a querystring?

2021-02-03 23:02 UTC, jobala requested changes
@ezkemboi @baywet trimming the whitespaces doesn't solve this issue. Odata query parameters come after the ?. @ezkemboi can you implement a URL validator for the path before a querystring?

2021-02-04 03:25 UTC, ezkemboi commented
@jobala, I will work on the changes.

2021-02-04 13:57 UTC, baywet commented
@jobala Thanks for double checking. I was looking into the nature of the change without knowing the code base very well but I didn't test the change myself.

2021-02-18 07:12 UTC, ezkemboi commented
@jobala, I have been busy a little, but I will try to work on the changes requested over this weekend.

2021-02-22 16:14 UTC, ElinorW commented
> @jobala, I have been busy a little, but I will try to work on the changes requested over this weekend.

Hey @ezkemboi any progress on this?

2021-02-22 21:03 UTC, ezkemboi commented
@ElinorW  I did not manage to work on this weekend, I had an interview this Monday and I was preparing for it over the weekend.

2021-04-12 16:17 UTC, ddyett commented
@ezkemboi are you still planning to work on this?

2021-06-22 09:38 UTC, thewahome commented
Thanks so much @ezkemboi for contributing to this. 

It has been open for a long time and taking advantage of the new code changes, I am closing this to work on it based on the below quoted suggestion

> Instead of running this magically should we instead have a url validation error message?

I will rope you in to see how it goes.

2021-06-22 09:38 UTC, closed without merging

2021-07-13 04:25 UTC, ezkemboi commented
I will double-check on this PR and its request and see if there is the best way, I can get a new PR out of it based on @jobala requests and comments highlighted previously.