Fix: Adaptive cards instrumentation
microsoftgraph/microsoft-graph-explorer-v4 pull request #849
Opened 2021-02-15 12:12 UTC by ElinorW

## Overview

Adds instrumentation when a user clicks on the JSON Schema tab under Adaptive Cards
Fixes #840

2021-02-15 15:08 UTC, thewahome commented on src/app/views/query-response/adaptive-cards/AdaptiveCard.tsx
> +
There may be no need for the switch case at this point. The telemetry tab click  event can be called immediately

2021-02-15 15:10 UTC, thewahome requested changes

2021-02-16 07:21 UTC, thewahome approved these changes

2021-02-16 08:08 UTC, merged

2021-02-17 00:53 UTC, millicentachieng commented on src/app/views/query-response/adaptive-cards/AdaptiveCard.tsx
> +      QuerySignature: `${query.selectedVerb} ${sanitizedUrl}`
@ElinorW FYI